---
- name: region
  win_region:
    format: us-west-2
- name: Touch a file (creates if not present, updates modification time if present)
  win_file:
    path: C:\Users\hari.txt
    state: touch
- name: Directory
  win_file:
    path: C:\Users\hari
    state: directory
